// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
logicals primR_are_equal_f(doubles x, doubles y, double eps);
extern "C" SEXP _primitiveR_primR_are_equal_f(SEXP x, SEXP y, SEXP eps) {
  BEGIN_CPP11
    return cpp11::as_sexp(primR_are_equal_f(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(eps)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _primitiveR_primR_are_equal_f(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_primitiveR_primR_are_equal_f", (DL_FUNC) &_primitiveR_primR_are_equal_f, 3},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_primitiveR(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
