# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

primR_are_equal_f <- function(x, y, eps) {
    .Call('_primitiveR_primR_are_equal_f', PACKAGE = 'primitiveR', x, y, eps)
}

