# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
    tags-ignore: 
      - 'v*'
  pull_request:
    branches: [ master ]
    tags-ignore: 
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 4.0
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.0.3
      
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      
      - name: Get dependencies for integration testing
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(pkgdir = ".", dependencies = NA), ".github/packages.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache installed R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/packages.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      
      - name: Install dependencies
        run: |
          remotes::install_deps(pkgdir = ".", dependencies = NA)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("roxygen2")
          remotes::install_cran("testthat")
        shell: Rscript {0}
                  
      - name: Build metadata
        run: |
          Rcpp::compileAttributes()
          roxygen2::roxygenize()
        shell: Rscript {0}
        
      - name: Build & Check package
        run: |
          rcmdcheck::rcmdcheck(path = ".", args = c("--no-manual"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
        
      - uses: actions/upload-artifact@v2.2.1
        with: 
          name: Package
          path: ./primitiveR*gz
        
